### ISSUE TITLE
Generate image for golang development

### ISSUE THREAD

**Issue by CodeBear801** [wangyoucao577/containers#4]
- inherit from `telenavmap/osrm-backend-dev`

## Option 1: use container as build/test system
```
docker build -t go-dev:v1 .

// enter docker image
docker run --rm -v /YourLocalPath:/workspace -it go-dev:v1 /bin/bash

// run commands
docker run --rm -v /YourLocalPath:/workspace  go-dev:v1 make test
docker run --rm -v /YourLocalPath:/workspace  go-dev:v1 make install
```

## Option 2: development in remote container

- Add `.devcontainer.json`, will trigger vscode to reopen in container

step 1: 
```
// add vscode to PATH, or you could run following command on mac
// sudo ln -fs "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code" /usr/local/bin/
code .
```
step 2: select `reopen in container`
![image](https://user-images.githubusercontent.com/16873751/86299452-2906af00-bbb5-11ea-8d23-bc49f0af8715.png)
 It will:
      - mapping your local code into `$GOPATH`
      
step 3: happy dev

Not finished:
     - enable `vs-plugins` in remote container when start up

You could experiment here: https://github.com/CodeBear801/containers/tree/feature/golang-dev

**Comment by wangyoucao577** [comment]
It's not necessary to inherit from `telenavmap/osrm-backend-dev`, just refer to [its dockerfile](https://github.com/Telenav/osrm-backend/blob/master/docker-orchestration/osrm-backend-dev/Dockerfile) and write your own one will be simpler and better. Actually the only thing need to do is remove the `C++` and `Lua` dependencies. 

The option1 might be useless(at least to me) since setup `Go`  build env on local is quite easy.

**Comment by wangyoucao577** [comment]
The `.devcontainer.json`..I have to say that Microsoft ships an amazing powerful tool to developers! It'll be so close to one-click developing environment setup, fantastic! Moreover, [microsoft's devcontainers](https://github.com/microsoft/vscode-dev-containers) has showed a lot of very good examples already. Even personally I prefer `Remote-SSH` rather than `Remote-Containers` due to performance, it still be very useful for some quick use case. 

- [microsoft's go devcontainer example](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/go), FYI. 
- [Developing inside a container on a remote Docker host](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host) could be a very useful improvement when leverage the devcontainer.

**Comment by CodeBear801** [comment]
That's great reference, I think we could fork one as our team's standard development env.

Update:
I have similar idea with the one in `microsoft's go devcontainer example`, will experiment to put those tools in container
```
    && GOPATH=/tmp/gotools GO111MODULE=on go get -v golang.org/x/tools/gopls@latest 2>&1 \
    && GOPATH=/tmp/gotools GO111MODULE=on go get -v \
        honnef.co/go/tools/...@latest \
        golang.org/x/tools/cmd/gorename@latest \
        golang.org/x/tools/cmd/goimports@latest \
        golang.org/x/tools/cmd/guru@latest \
        golang.org/x/lint/golint@latest \
        github.com/mdempsky/gocode@latest \
        github.com/cweill/gotests/...@latest \
        github.com/haya14busa/goplay/cmd/goplay@latest \
        github.com/sqs/goreturns@latest \
        github.com/josharian/impl@latest \
        github.com/davidrjenni/reftools/cmd/fillstruct@latest \
        github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest  \
        github.com/ramya-rao-a/go-outline@latest  \
        github.com/acroca/go-symbols@latest  \
        github.com/godoctor/godoctor@latest  \
        github.com/rogpeppe/godef@latest  \
        github.com/zmb3/gogetdoc@latest \
        github.com/fatih/gomodifytags@latest  \
        github.com/mgechev/revive@latest  \
        github.com/go-delve/delve/cmd/dlv@latest 2>&1 \
```
I tried some during development, but failed with compiling.  Will try again.
https://github.com/CodeBear801/containers/tree/feature/golang-dev/docker/golang-dev

**Comment by CodeBear801** [comment]
> It's not necessary to inherit from `telenavmap/osrm-backend-dev`, just refer to [its dockerfile](https://github.com/Telenav/osrm-backend/blob/master/docker-orchestration/osrm-backend-dev/Dockerfile) and write your own one will be simpler and better. Actually the only thing need to do is remove the `C++` and `Lua` dependencies.
> 
> The option1 might be useless(at least to me) since setup `Go` build env on local is quite easy.

My thinking is:
- Understanding `GoPATH` is important, but for new developer it will be friendly if everything is set up and they could directly write code, it will help more people join us for development using `golang`
- Consider later we might use multiple languages/frameworks for development, it would be easier if we setup all dev env in containers, especially currently for me, I have containers for following purpose:
    + OSRM development
    + Data science
    + Data processing with python tools, such as pyspark, pykafka, pyelesticsearch
    + Java based image which contains JDK8 and JDK11 in case I need play some JAVA code
    + npm environment for node
- I think later, it will be great if we could have following containers
    + C++11&14 development, related plugins and tools
    + python3, pylint, pytest, etc
    + golang, golint,  

Update:
I think https://github.com/microsoft/vscode-dev-containers/tree/master/containers provides great templates, the reason for having ourselves config files is for basic settings, such as useful plugins(pylint, static check)

**Comment by CodeBear801** [comment]
For remote development, I think it will be popular.  Take Kaggle as example, https://www.kaggle.com/liuxun801/from-eda-to-the-top-lb-0-367, besides code, it has all development environment set up in Cloud side.

I think open source project should also adopt this, it should be easily to modify code/running tests in remote virtual machine, which has all dev environment set up, such as vscode's config.

**Comment by wangyoucao577** [comment]
From my personal perspective, I prefer to have a all-in-one dev container that contains all the dependencies you listed above.  Maybe we can name it "all-in-one-dev"? Haha.

**Comment by CodeBear801** [comment]
That's my dream before.
I think another description is: have all development env environment in one docker image, and use docker compose to set up running environment in local or single node. 

FYI
https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/
